//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K7Burguer.Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HamburgueriaVerityEntities : DbContext
    {
        public HamburgueriaVerityEntities()
            : base("name=HamburgueriaVerityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batata> Batata { get; set; }
        public virtual DbSet<Bebida> Bebida { get; set; }
        public virtual DbSet<Hamburguer> Hamburguer { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
    }
}
