//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K7Burguer.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public long CodPedido { get; set; }
        public Nullable<int> CodHamburguer { get; set; }
        public Nullable<int> CodBebida { get; set; }
        public Nullable<int> CodBatata { get; set; }
        public decimal ValorTotal { get; set; }
        public Nullable<int> QtdHamburguer { get; set; }
        public Nullable<int> QtdBebida { get; set; }
        public System.DateTime DataPedido { get; set; }
        public Nullable<int> QtdBatata { get; set; }
    
        public virtual Batata Batata { get; set; }
        public virtual Bebida Bebida { get; set; }
        public virtual Hamburguer Hamburguer { get; set; }
    }
}
